local dap, dapgo, vscode = require('dap'), require('dap-go'), require('dap.ext.vscode')
dapgo.setup()
vim.keymap.set('n', '<F4>', function() dap.repl.toggle({height=10}) end, {})
vim.keymap.set('n', '<F5>', function() vscode.load_launchjs('.vscode/launch.json'); dap.continue() end, {expr = true})
vim.keymap.set('n', '<F8>', function() dap.clear_breakpoints() end, {expr = true})
vim.keymap.set('n', '<F9>', function() dap.toggle_breakpoint() end, {expr = true})
vim.keymap.set('n', '<F10>', function() dap.step_over() end, {expr = true})
vim.keymap.set('n', '<F11>', function() dap.step_into() end, {expr = true})
vim.keymap.set('n', '<F12>', function() dap.step_out() end, {expr = true})
