filetype plugin indent on
syntax on
let mapleader="\<Space>"
let loaded_matchparen=1
set nohlsearch nobackup nowritebackup noswapfile nowrap
set completeopt-=preview
set grepprg=rg\ --vimgrep
set hidden ignorecase shiftwidth=4 tabstop=4 laststatus=0 mouse=a ttyfast timeoutlen=100
set wildignore+=.git/* wildmode=longest,list,full
nn <silent> <leader>e :Ex<CR>
nn <silent> <leader>q :%bw!<CR>
nn <F3> :set nu!<CR>
nn <leader>f /
nn n nzz
vn < <gv
vn > >gv
let g:netrw_banner = 0
let g:netrw_cursor = 0
let g:netrw_dirhistmax = 0
colo light
