set rtp+=~/.vim-plugins/LanguageClient-neovim
set rtp+=~/.vim-plugins/skim

filetype plugin indent on
syntax on
let mapleader="\<Space>"

set autoread
set backspace=indent,eol,start
set hidden
set ignorecase
set incsearch
set lazyredraw
set mouse=a
set nocursorline
set noerrorbells visualbell t_vb=""
set nofixendofline
set noswapfile
set nowrap
set number
set path+=**
set scrolljump=8 " ttyscroll=3
set shiftwidth=2 tabstop=2
set shortmess+=c
set synmaxcol=200 ttyfast
set updatetime=300
set wildignore+=.git/*,.gradle/*,node_modules/*
set wildmenu wildmode=longest,list,full

im <F1> <Nop>
im jj <ESC>
nn j gj
nn k gk
nn <F1> :set hls!<CR>
nn <F2> :set invlist!<CR>
nn <F3> :set nonu!<CR>
nn <F4> :set cursorline!<CR>
nn <silent> <leader>e :Explore<CR>
nn <silent> <leader>q :%bd!<CR>
nm <silent> <C-t> :SK --color=bw<CR>
nm <silent> <C-S-p> :pc<CR>

vn < <gv
vn > >gv

au BufWritePre * :%s/\s\+$//e " strip trailing whitespace on save

let g:netrw_banner = 0
let g:netrw_cursor = 0
let g:netrw_dirhistmax = 0
let g:netrw_preview = 1

let g:LanguageClient_diagnosticsList = 'Location'
let g:LanguageClient_rootMarkers = {
\ 'javascript': ['package.json', 'tsconfig.json'],
\ 'typescript': ['tsconfig.json', 'package.json'],
\ }
let g:LanguageClient_serverCommands = {
\ 'javascript': ['javascript-typescript-stdio'],
\ 'typescript': ['javascript-typescript-stdio'],
\ }
nnoremap <leader><leader> :call LanguageClient_contextMenu()<CR>
set completefunc=LanguageClient#complete

colo apprentice
au! GuiEnter * silent set visualbell t_vb=""
if has("gui_running")
  set go=""
  set guicursor+=a:blinkon0
  if has("mac")
    set guifont=Menlo:h14
  elseif has("unix")
    set guifont=Input\ 11
  endif
endif
