call plug#begin()
Plug 'junegunn/fzf', { 'dir': '~/.fzf' }
Plug 'tpope/vim-commentary'
Plug 'vim-scripts/HTML-AutoCloseTag', { 'for': 'html' }
" Plug 'w0rp/ale', { 'for': 'javascript, typescript' }
Plug 'leafgarland/typescript-vim', { 'for': 'typescript' }
call plug#end()

filetype plugin indent on
syntax on
let mapleader="\<Space>"

set autoread
set backspace=indent,eol,start
set bg=dark
set dir=/tmp
set expandtab
set grepprg=rg\ --vimgrep
set hidden
set ignorecase
set incsearch
set lazyredraw
set laststatus=0
set mouse=a
set nocursorline
set noeol
set noerrorbells vb t_vb=""
set nonumber
set nowrap
set path+=**
set ruler
set scrolljump=8 " ttyscroll=3
set shiftwidth=2 tabstop=2
set synmaxcol=200 ttyfast
set wildignore+=.git/*,.gradle/*,node_modules/*
set wildmenu wildmode=longest,list,full

im <F1> <Nop>
im jj <ESC>
nn j gj
nn k gk
nn <F1> :set hls!<CR>
nn <F2> :set invlist!<CR>
nn <F3> :set nonu!<CR>
nn <silent> <leader>e :Explore<CR>
nn <silent> <leader>q :%bd!<CR>
nm <silent> <C-t> :FZF<CR>
nm <silent> <C-p> :pc<CR>
vn < <gv
vn > >gv

au BufWritePre * :%s/\s\+$//e " strip trailing whitespace on save
au FileType *.go,c,cpp,groovy,java,jsp,python setlocal noet sw=4 ts=4

let g:netrw_banner = 0
let g:netrw_cursor = 0
let g:netrw_preview = 1

" let g:ale_fix_on_save = 1
" let g:ale_lint_on_text_changed = 'never'
" let g:ale_lint_on_enter = 0
" let g:ale_linters = {'javascript': ['eslint']}

colo wombat256
au! GuiEnter * silent set visualbell t_vb=""
if has("gui_running")
  set go=""
  set guicursor+=a:blinkon0
  if has("mac")
    set guifont=Menlo:h14
  elseif has("unix")
    set guifont=Input\ 11
  endif
endif